remote_theme: shalwxy/jekyll-theme-satellite

title: "Shalwxy"
description: "My awesome blog using Satellite theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: shalwxy@gmail.com
github_username: shalwxy
twitter_username: shalwxy
instagram_username: shalwxy
linkedin_username: seungha-lee-2aa442229
facebook_username: 61579726485028

# External API
giscus_repo: "shalwxy/shalwxy.github.io"
giscus_repoId: "R_kgDOPm0RSg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOPm0RSs4CuxMV"
goatcounter_code: "shalwxy"
google_analytics: "G-GWLCL52Q93"

baseurl: ""

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy
  - jekyll-remote-theme

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

kramdown:
  input: GFM
  hard_wrap: true

include:
  - "_pages"
